app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"

# Default routes for Sonata Admin
admin_area:
   resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
   prefix: /admin

# Allow generation of routes for our admins. The important part here is the type.
_sonata_admin:
   resource: .
   type: sonata_admin
   prefix: /admin
