security:

  # What hashing library we will use to encode passwords
  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt

  # Some user roles and an inheritance structure
  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  # Services capable of providing authentication
  providers:
    fos_userbundle:
      id: fos_user.user_provider.username

  # Request matcher / listener definition
  firewalls:

    # A firewall for bypassing security when using the development environment
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      # Which set of URLs will this firewall rule cover
      pattern: ^/
      form_login:
        provider: fos_userbundle
        csrf_token_generator: security.csrf.token_manager
      logout:       true
      # Allow anonymous users by default
      anonymous:    true

  # URL rules to authenticate against specific user roles
  access_control:
    # IS_AUTHENTICATED_ANONYMOUSLY is every user
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }