security:
   # What hashing library we will use to encode passwords
   encoders:
       FOS\UserBundle\Model\UserInterface: bcrypt
   # Some user roles and the inheritance structure
   role_hierarchy:
       ROLE_ADMIN:       ROLE_USER
       ROLE_SUPER_ADMIN: ROLE_ADMIN
   # Services capable of providing authentication
   providers:
       fos_userbundle:
           id: fos_user.user_provider.username
   # Request matcher / listener definition
   firewalls:
       dev:
           pattern: ^/(_(profiler|wdt)|css|images|js)/
           security: false
       main:
           pattern: ^/
           form_login:
               provider: fos_userbundle
               csrf_token_generator: security.csrf.token_manager
           logout:       true
           anonymous:    true

   # URL rules to authenticate against
   access_control:
       # IS_AUTHENTICATED_ANONYMOUSLY is all users
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin/, role: ROLE_ADMIN }
