# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.blog_manager:
    class: AppBundle\Service\BlogManager

  app.sonata.admin.post:
    class: AppBundle\Admin\PostAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Blog Management", label: "Posts"}
    arguments: [~, AppBundle\Entity\Post, ~]
    calls:
      - [ setTranslationDomain, [AppBundle]]
