# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  sonata.admin.post:
    class: AppBundle\Admin\PostAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Blog Management", label: "Posts"}
    arguments: [~, AppBundle\Entity\Post, ~]
    calls:
      - [ setTranslationDomain, [AppBundle]]
