version: '2'

services:

  project_toolchain:
    env_file: .env
    build:
      context: docker/project_toolchain
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    image: symfony_tutorial/project_toolchain
    stdin_open: true
    tty: true
    links:
      - database
    volumes:
      - ./site:/var/www/html

  nginx:
    image: nginx:1.10.3-alpine
    ports:
      - 8086:80
    volumes_from:
     - project_toolchain
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - phpfpm
    depends_on:
      - phpfpm

  phpfpm:
    env_file: .env
    build:
      context: docker/php_fpm
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    image: symfony_tutorial/php_fpm
    links:
      - database
    volumes_from:
     - project_toolchain

  database:
      image: mariadb:10.1
      # If you want to change the DB credentials, remember to update
      # the Symfony config file in site/app/config/paramters.yml
      environment:
          - MYSQL_ROOT_PASSWORD=docker_root_password
          - MYSQL_DATABASE=symfony_tutorial
          - MYSQL_USER=symfony_db_user
          - MYSQL_PASSWORD=symfony_db_password
      volumes:
          - ./docker/data/mariadb:/var/lib/mysql
